"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactFlowProvider } from "@xyflow/react";
import { LiveblocksProvider, RoomProvider } from "@liveblocks/react/suspense";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LiveblocksProvider publicApiKey={"pk_prod_hxsifK11dNff7o_wuiZQx9FH2z5jvTZmS09I6wFNacLK924Rwh0gvA1WL3s6mldT"}>
          {/* TODO: replace this id */}
          <RoomProvider id="MY_ROOM_ID_REPLACE_ME"> 
            <ReactFlowProvider>
              {children}
            </ReactFlowProvider>
          </RoomProvider>
        </LiveblocksProvider>
      </body>
    </html>
  );
}
